# Main Terraform configuration for {{PROJECT_NAME}}
# Generated by Meta-Repo Seeding System

terraform {
  required_version = ">= 1.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 4.0"
    }
  }

  # Remote state configuration
  backend "s3" {
    # Configure for your preferred backend
    # bucket = "{{PROJECT_NAME}}-terraform-state"
    # key    = "{{PROJECT_NAME}}/terraform.tfstate"
    # region = "us-west-2"
  }
}

# Local values for reuse
locals {
  project_name = "{{PROJECT_NAME}}"
  owner       = "{{GITHUB_USERNAME}}"
  environment = var.environment
  
  common_tags = {
    Project     = local.project_name
    Owner       = local.owner
    Environment = local.environment
    ManagedBy   = "terraform"
  }
}

# Example resource - customize for your needs
resource "random_id" "deployment_id" {
  byte_length = 8
  
  keepers = {
    project = local.project_name
  }
}

# Output deployment info
output "deployment_id" {
  value = random_id.deployment_id.hex
  description = "Unique deployment identifier"
}

# Include provider-specific modules
# Uncomment the provider you want to use:

# module "aws_infrastructure" {
#   source = "./aws"
#   
#   project_name = local.project_name
#   environment  = local.environment
#   common_tags  = local.common_tags
# }

# module "azure_infrastructure" {
#   source = "./azure"
#   
#   project_name = local.project_name
#   environment  = local.environment
#   common_tags  = local.common_tags
# }

# module "gcp_infrastructure" {
#   source = "./gcp"
#   
#   project_name = local.project_name
#   environment  = local.environment
#   common_tags  = local.common_tags
# }
