# Outputs for {{PROJECT_NAME}} Infrastructure
# Generated by Meta-Repo Seeding System

output "project_name" {
  description = "Name of the project"
  value       = local.project_name
}

output "environment" {
  description = "Current environment"
  value       = var.environment
}

output "region" {
  description = "Primary deployment region"
  value       = var.region
}

# Infrastructure endpoints and connection info
# Uncomment and customize based on your infrastructure:

# output "load_balancer_url" {
#   description = "Load balancer URL"
#   value       = module.aws_infrastructure.load_balancer_url
# }

# output "database_endpoint" {
#   description = "Database connection endpoint"
#   value       = module.aws_infrastructure.database_endpoint
#   sensitive   = true
# }

# output "application_url" {
#   description = "Application URL"
#   value       = "https://${var.domain_name}"
# }

# output "monitoring_dashboard" {
#   description = "Monitoring dashboard URL"
#   value       = module.aws_infrastructure.monitoring_dashboard_url
# }

# Security and access information
# output "vpc_id" {
#   description = "VPC ID"
#   value       = module.aws_infrastructure.vpc_id
# }

# output "security_group_ids" {
#   description = "Security group IDs"
#   value       = module.aws_infrastructure.security_group_ids
# }

# Kubernetes cluster info (if applicable)
# output "cluster_name" {
#   description = "Kubernetes cluster name"
#   value       = module.aws_infrastructure.cluster_name
# }

# output "cluster_endpoint" {
#   description = "Kubernetes cluster endpoint"
#   value       = module.aws_infrastructure.cluster_endpoint
#   sensitive   = true
# }
