# Provider configurations for {{PROJECT_NAME}}
# Generated by Meta-Repo Seeding System

# AWS Provider Configuration
provider "aws" {
  region = var.region
  
  default_tags {
    tags = local.common_tags
  }
}

# Azure Provider Configuration
# Uncomment if using Azure
# provider "azurerm" {
#   features {}
# }

# Google Cloud Provider Configuration  
# Uncomment if using GCP
# provider "google" {
#   project = "{{PROJECT_NAME}}-gcp"
#   region  = var.region
# }

# Additional providers as needed
# provider "kubernetes" {
#   host                   = module.aws_infrastructure.cluster_endpoint
#   cluster_ca_certificate = base64decode(module.aws_infrastructure.cluster_ca_certificate)
#   token                  = module.aws_infrastructure.cluster_auth_token
# }

# provider "helm" {
#   kubernetes {
#     host                   = module.aws_infrastructure.cluster_endpoint
#     cluster_ca_certificate = base64decode(module.aws_infrastructure.cluster_ca_certificate)
#     token                  = module.aws_infrastructure.cluster_auth_token
#   }
# }
