name: Bug Report
description: Report a defect, error, or unexpected behavior
title: "[BUG] "
labels: ["bug", "priority: medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: Clear and concise description of the bug
      placeholder: Describe what the bug is...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-actual
    attributes:
      label: 📊 Expected vs Actual Behavior
      description: What you expected vs what actually happened
      placeholder: |
        **Expected:** A clear description of what you expected to happen
        **Actual:** A clear description of what actually happened
      value: |
        **Expected:** 
        
        **Actual:** 
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 💻 Environment
      description: System information where the bug occurs
      placeholder: |
        - OS: [e.g. Windows 11, macOS 12.3, Ubuntu 22.04]
        - Python version: [e.g. 3.9.7]
        - Branch/commit: [e.g. develop, v1.0.0, commit hash]
        - Terminal: [e.g. PowerShell, bash, zsh]
      value: |
        - OS: 
        - Python version: 
        - Branch/commit: 
        - Terminal: 
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: ❌ Error Output
      description: Any error messages, stack traces, or relevant output
      placeholder: Paste any error messages or relevant output here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here or paste image URLs...
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this bug?
      options:
        - Medium (default - normal bug)
        - High (major feature broken, blocks work)
        - Low (cosmetic issue, minor inconvenience)
        - Critical (security issue, data loss, system crash)
    validations:
      required: true

  - type: textarea
    id: proposed-fix
    attributes:
      label: 🔧 Proposed Fix
      description: If you have suggestions for fixing this bug, please describe them
      placeholder: If you have ideas about what might be causing this or how to fix it...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this report
          required: true
        - label: I can reproduce this issue consistently
          required: false
        - label: I am willing to help test a fix
          required: false