name: PR Issue Link Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-issue-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate PR links to issues
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
      run: |
        echo "Validating PR properly links to issues..."
        echo "DEBUG: Checking PR body for issue links..."
        
        # Simple check for auto-close keywords
        if echo "$PR_BODY" | grep -q -i "closes #[0-9]\+\|fixes #[0-9]\+\|resolves #[0-9]\+"; then
          echo "SUCCESS: Found auto-close keywords in PR"
          echo "$PR_BODY" | grep -i "closes #\|fixes #\|resolves #" || true
          
        elif echo "$PR_BODY" | grep -q -i "related to #[0-9]\+"; then
          echo "WARNING: Found references but no auto-close keywords"
          
        elif echo "$PR_BODY" | grep -q -i "no related issues\|no existing issues\|doesn't address existing"; then
          echo "SUCCESS: PR explains no related issues"
          
        else
          echo "ERROR: PR must link to issues or explain why none exist"
          echo "Required: 'Closes #123' or 'Fixes #456' or 'Resolves #789'"
          exit 1
        fi
        
        echo "Validation passed!"
