name: PR Issue Link Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-issue-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate PR links to issues
      run: |
        echo "🔍 Validating PR properly links to issues..."
        
        PR_BODY="${{ github.event.pull_request.body }}"
        
        # Check for auto-close keywords (case-insensitive)
        if echo "$PR_BODY" | grep -iE "(closes|fixes|resolves) #[0-9]+"; then
          echo "✅ PR properly links to issues with auto-close keywords"
          
          # Extract and display linked issues
          linked_issues=$(echo "$PR_BODY" | grep -ioE "(closes|fixes|resolves) #[0-9]+" || true)
          if [ -n "$linked_issues" ]; then
            echo ""
            echo "📋 Issues that will auto-close when PR merges:"
            echo "$linked_issues"
          fi
          
        # Check for reference-only links
        elif echo "$PR_BODY" | grep -iE "related to #[0-9]+"; then
          echo "⚠️ PR contains issue references but no auto-close keywords"
          echo "Consider using: Closes #123, Fixes #456, or Resolves #789"
          echo "References found:"
          echo "$PR_BODY" | grep -ioE "related to #[0-9]+" || true
          
        # Check for explanation of no related issues
        elif echo "$PR_BODY" | grep -iE "(no related issues|no existing issues|doesn't address existing)"; then
          echo "✅ PR explains why it doesn't address existing issues"
          
        else
          echo "❌ PR must link to issues or explain why none exist"
          echo ""
          echo "Required formats:"
          echo "  - Closes #123 (auto-closes issue when PR merges)"
          echo "  - Fixes #456 (auto-closes issue when PR merges)"  
          echo "  - Resolves #789 (auto-closes issue when PR merges)"
          echo "  - Related to #123 (reference only, doesn't auto-close)"
          echo "  - Or explain why no existing issues are addressed"
          echo ""
          echo "This ensures proper issue management and prevents orphaned work."
          exit 1
        fi
        
        echo ""
        echo "✅ PR issue linking validation passed!"
